d3.select("body")
	.on("click", function(){
		d3.select("#h1")
			.transition()
			.duration(1200)
			.style("opacity",0)
		d3.selectAll(".s2")
			.transition()
			.delay(800)
			.duration(1200)
			.style("opacity",1)
		d3.select("#t1")
			.transition()
			.duration(1200)
			.style("margin-left","525px")
		d3.select("#t2")
			.transition()
			.duration(1200)
			.style("margin-left","332px")
		// d3.select("#t3")
		// 	.transition()
		// 	.duration(1000)
		// 	.style("margin-left","-53px")

	})
