var mouseover = {
	"higher": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"payroll":{"format": "foo", "label" : "bar"},
		"nonpayroll":{"format": "foo", "label" : "bar"}],
	"corrections": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"payroll":{"format": "foo", "label" : "bar"},
		"nonpayroll":{"format": "foo", "label" : "bar"}],
	"medicaid": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"spending-per":{"format": "foo", "label" : "bar"}],
	"ssi": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"spending-per":{"format": "foo", "label" : "bar"}],
	"tanf": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"spending-per":{"format": "foo", "label" : "bar"}],
	"ccdf": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"spending-per":{"format": "foo", "label" : "bar"}],	
	"housing": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"payroll":{"format": "foo", "label" : "bar"},
		"nonpayroll":{"format": "foo", "label" : "bar"}],
	"admin": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"payroll":{"format": "foo", "label" : "bar"},
		"nonpayroll":{"format": "foo", "label" : "bar"}],
	"resources": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"payroll":{"format": "foo", "label" : "bar"},
		"nonpayroll":{"format": "foo", "label" : "bar"}],
	"parks": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"payroll":{"format": "foo", "label" : "bar"},
		"nonpayroll":{"format": "foo", "label" : "bar"}],
	"utilities": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"payroll":{"format": "foo", "label" : "bar"},
		"nonpayroll":{"format": "foo", "label" : "bar"}],
	"k12": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"payroll":{"format": "foo", "label" : "bar"},
		"nonpayroll":{"format": "foo", "label" : "bar"}],
	"fire": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"payroll":{"format": "foo", "label" : "bar"},
		"nonpayroll":{"format": "foo", "label" : "bar"}],
	"police": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"payroll":{"format": "foo", "label" : "bar"},
		"nonpayroll":{"format": "foo", "label" : "bar"}],
	"highway": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"payroll":{"format": "foo", "label" : "bar"},
		"nonpayroll":{"format": "foo", "label" : "bar"}],
	"transit": [
		"spending":{"format": "dollars", "label" : "per state resident"},
		"demographics":{"format": "foo", "label" : "bar"},
		"eligibility":{"format": "foo", "label" : "bar"},
		"takeup":{"format": "foo", "label" : "bar"},
		"units":{"format": "foo", "label" : "bar"},
		"payroll":{"format": "foo", "label" : "bar"},
		"nonpayroll":{"format": "foo", "label" : "bar"}]
}